# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'Repositorio de código del proyecto de la localización venezolana
    para el software de gestión integral Odoo. La localización española de Odoo incluye:
    - Módulos para adaptar el sistema a los requisitos fiscales y contables venezolanas.
    - Traducciones a los términos oficiales del país.'
repo_name: Localización venezolana de Odoo
repo_slug: l10n-venezuela
repo_website: https://github.com/OCA/l10n-venezuela
use_pyproject_toml: false
use_ruff: false

