from . import product
from . import product_pricelist
from . import res_currency_rate
from . import res_currency
from . import res_config_settings
from . import pos_config
from . import pos_order
from . import pos_payment
from . import pos_payment_method
from . import pos_session
from . import pos_session_cash_box
