from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

_L10N_VE_IGTF_ACCOUNT_TYPES = ("liability_current", "liability_non_current")


class ResCompany(models.Model):
    _inherit = "res.company"

    l10n_ve_igtf_feature_active = fields.Boolean(
        string="IGTF regime active",
        compute="_compute_l10n_ve_igtf_feature_active",
        store=True,
        help=(
            "Technical: IGTF applies for Venezuela companies with "
            "taxpayer type Special."
        ),
    )

    l10n_ve_igtf_currency_ids = fields.Many2many(
        comodel_name="res.currency",
        relation="l10n_ve_igtf_res_company_currency_rel",
        column1="company_id",
        column2="currency_id",
        string="IGTF Currencies",
        help="Currencies for which IGTF should apply (for example, USD).",
    )
    l10n_ve_igtf_allow_invoice_accrual = fields.Boolean(
        string="IGTF en facturas",
        default=True,
        help=(
            "Si está activo, al confirmar facturas de venta en "
            "monedas IGTF (p. ej. USD) "
            "se generan líneas de IGTF en el asiento. Si está "
            "desactivado, el IGTF solo "
            "se calcula y registra en cobros y pagos."
        ),
    )

    l10n_ve_igtf_account_id = fields.Many2one(
        comodel_name="account.account",
        string="IGTF Account",
        check_company=True,
        domain=[("account_type", "in", _L10N_VE_IGTF_ACCOUNT_TYPES)],
        help="Liability account used to record IGTF generated by payments.",
    )
    l10n_ve_igtf_percent = fields.Float(
        string="IGTF (%)",
        default=3.0,
        help="IGTF percentage to split from the payment and post to the IGTF account.",
    )

    def _l10n_ve_igtf_is_active(self):
        self.ensure_one()
        if (
            not self.account_fiscal_country_id
            or self.account_fiscal_country_id.code != "VE"
        ):
            return False
        if self.taxpayer_type != "special":
            return False
        return True

    def _l10n_ve_invoice_tag_include_igtf_notice(self):
        self.ensure_one()
        if not super()._l10n_ve_invoice_tag_include_igtf_notice():
            return False
        return self._l10n_ve_igtf_is_active()

    @api.depends(
        "account_fiscal_country_id",
        "partner_id.taxpayer_type",
    )
    def _compute_l10n_ve_igtf_feature_active(self):
        for company in self:
            company.l10n_ve_igtf_feature_active = company._l10n_ve_igtf_is_active()

    def _l10n_ve_get_default_igtf_account(self):
        self.ensure_one()
        Account = self.env["account.account"].with_company(self)
        igtf_account = Account.search(
            [
                ("account_type", "in", _L10N_VE_IGTF_ACCOUNT_TYPES),
                "|",
                ("name", "ilike", "IGTF"),
                ("code", "=", "2102003"),
            ],
            limit=1,
        )
        return igtf_account

    def _l10n_ve_fix_igtf_account_configuration(self):
        for company in self:
            if (
                not company.account_fiscal_country_id
                or company.account_fiscal_country_id.code != "VE"
            ):
                continue
            account = company.l10n_ve_igtf_account_id
            if account and account.account_type in _L10N_VE_IGTF_ACCOUNT_TYPES:
                continue
            default_account = company._l10n_ve_get_default_igtf_account()
            if default_account:
                company.l10n_ve_igtf_account_id = default_account

    @api.constrains("l10n_ve_igtf_account_id")
    def _check_l10n_ve_igtf_account_type(self):
        for company in self:
            account = company.l10n_ve_igtf_account_id
            if not account:
                continue
            if account.account_type not in _L10N_VE_IGTF_ACCOUNT_TYPES:
                raise ValidationError(
                    _(
                        "La cuenta de IGTF debe ser de tipo pasivo "
                        "(corriente o no corriente)."
                    )
                )

    @api.constrains(
        "l10n_ve_igtf_account_id",
        "account_fiscal_country_id",
        "partner_id.taxpayer_type",
    )
    def _check_l10n_ve_igtf_account_required_for_special(self):
        if self.env.context.get("l10n_ve_skip_igtf_account_check"):
            return
        for company in self:
            if not company._l10n_ve_igtf_is_active():
                continue
            if not company.l10n_ve_igtf_account_id:
                raise ValidationError(
                    _(
                        "La cuenta de IGTF es obligatoria para compañías "
                        "con tipo de contribuyente Especial."
                    )
                )

    @api.constrains("l10n_ve_igtf_percent")
    def _check_l10n_ve_igtf_percent(self):
        """
        Validate that the configured IGTF percentage is within a valid range.

        Parameters
        ----------
        None

        Returns
        -------
        None

        Raises
        ------
        ValidationError
            If IGTF percentage is outside the [0, 100] interval.
        """
        for company in self:
            if (
                company.l10n_ve_igtf_percent < 0.0
                or company.l10n_ve_igtf_percent > 100.0
            ):
                raise ValidationError(_("IGTF percentage must be between 0 and 100."))
