# Copyright 2026 andyengit
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).

{
    "name": "Currency POS",
    "summary": "Multi-currency products and payments in Point of Sale",
    "version": "18.0.3.0.11",
    "development_status": "Beta",
    "category": "Point of Sale",
    "countries": ["ve"],
    "author": "andyengit, Odoo Community Association (OCA)",
    "maintainers": ["andyengit"],
    "website": "https://github.com/OCA/l10n-venezuela",
    "license": "LGPL-3",
    "depends": [
        "point_of_sale",
        "pos_sale",
        "pos_hr",
        "mail",
        "l10n_ve_product_currency",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/pos_config_views.xml",
        "views/pos_payment_method_views.xml",
        "views/pos_payment_views.xml",
        "views/pos_order_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "currency_pos/static/src/utils/currency_utils.js",
            "currency_pos/static/src/app/utils/payment_currency_utils.js",
            "currency_pos/static/src/app/utils/opening_cash_utils.js",
            "currency_pos/static/src/app/generic_components/currency_rates_widget/currency_rates_widget.xml",
            "currency_pos/static/src/app/generic_components/currency_rates_widget/currency_rates_widget.js",
            "currency_pos/static/src/app/screens/product_screen/product_screen.js",
            "currency_pos/static/src/app/screens/product_screen/product_screen.xml",
            "currency_pos/static/src/overrides/screens/product_screen/product_screen.js",
            "currency_pos/static/src/overrides/store/pos_store.js",
            "currency_pos/static/src/app/models/pos_order.js",
            "currency_pos/static/src/app/models/pos_payment.js",
            "currency_pos/static/src/overrides/models/product_product.js",
            "currency_pos/static/src/overrides/components/orderline/orderline.js",
            "currency_pos/static/src/overrides/components/orderline/orderline.xml",
            "currency_pos/static/src/overrides/components/order_widget/order_widget.js",
            "currency_pos/static/src/overrides/components/order_widget/order_widget.xml",
            "currency_pos/static/src/overrides/components/control_buttons/control_buttons.js",
            "currency_pos/static/src/overrides/components/control_buttons/control_buttons.xml",
            "currency_pos/static/src/app/screens/payment_screen/payment_screen.js",
            "currency_pos/static/src/app/screens/payment_screen/payment_screen.xml",
            "currency_pos/static/src/app/screens/payment_screen/payment_lines/payment_lines.js",
            "currency_pos/static/src/app/screens/payment_screen/payment_status/payment_status.js",
            "currency_pos/static/src/app/screens/receipt_screen/receipt/order_receipt.js",
            "currency_pos/static/src/app/screens/receipt_screen/receipt/order_receipt.xml",
            "currency_pos/static/src/app/store/opening_control_popup/opening_control_popup.js",
            "currency_pos/static/src/app/store/opening_control_popup/opening_control_popup.xml",
            "currency_pos/static/src/app/navbar/cash_move_popup/cash_move_popup.js",
            "currency_pos/static/src/app/navbar/cash_move_popup/cash_move_popup.xml",
            "currency_pos/static/src/app/navbar/closing_popup/closing_popup.js",
            "currency_pos/static/src/app/navbar/closing_popup/closing_popup.xml",
            "currency_pos/static/src/overrides/components/product_card/product_card.js",
            "currency_pos/static/src/overrides/components/product_card/product_card.xml",
            "currency_pos/static/src/overrides/components/product_configurator_popup/product_configurator_popup.js",
            "currency_pos/static/src/overrides/components/product_info_popup/product_info_popup.js",
            "currency_pos/static/src/overrides/components/product_info_popup/product_info_popup.xml",
        ],
        "web.assets_tests": [
            "currency_pos/static/tests/tours/**/*",
        ],
        "web.assets_unit_tests": [
            "currency_pos/static/src/app/utils/payment_currency_utils.js",
            "currency_pos/static/src/app/utils/opening_cash_utils.js",
            "currency_pos/static/tests/unit/**/*",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": False,
}
